ARG NODE_IMAGE=node:24.5.0-slim

FROM ${NODE_IMAGE} AS builder

RUN apt-get update && apt-get install -y python3 python3-pip sqlite3 && rm -rf /var/lib/apt/lists/*

WORKDIR /home/perplexica

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile --network-timeout 600000

COPY tsconfig.json next.config.mjs next-env.d.ts postcss.config.js drizzle.config.ts tailwind.config.ts ./
COPY src ./src
COPY public ./public
COPY drizzle ./drizzle

RUN mkdir -p /home/perplexica/data
RUN yarn build

ARG NODE_IMAGE=node:24.5.0-slim
FROM ${NODE_IMAGE}

RUN apt-get update && apt-get install -y python3 python3-pip sqlite3 && rm -rf /var/lib/apt/lists/*

WORKDIR /home/perplexica

COPY --from=builder /home/perplexica/public ./public
COPY --from=builder /home/perplexica/.next/static ./public/_next/static

COPY --from=builder /home/perplexica/.next/standalone ./
COPY --from=builder /home/perplexica/data ./data
COPY drizzle ./drizzle

RUN mkdir /home/perplexica/uploads
RUN yarn add --ignore-scripts playwright@^1.57.0 && \
    yarn playwright install --with-deps --only-shell chromium

EXPOSE 3000

CMD ["node", "server.js"]
